UPDATE SALESMAN SET grade = '200' WHERE SALESMAN_CITY = 'Rome';
UPDATE SALESMAN SET grade = '300' WHERE SALESMAN_NAME = 'James Hoog';
UPDATE SALESMAN SET salesman_name = 'Pierre' WHERE SALESMAN_NAME = 'Mclyon';

